---
apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: bggapp-deploy 
  namespace: bggns
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: bggapp-pod
  template:
    metadata:
      labels:
        app: bggapp-pod 
    spec:
      containers:
      - name: bggapp-pod-container
        image: chukmunnlee/bgg-app:nov-2025
        env:
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bggapp-secret
              key: BGG_DB_PASSWORD
        - name: BGG_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bggapp-cm
              key: BGG_DB_HOST
        - name: BGG_PORT
          valueFrom:
            configMapKeyRef:
              name: bggapp-cm
              key: BGG_PORT
        - name: BGG_DB_USER
          valueFrom:
            configMapKeyRef:
              name: bggapp-cm
              key: BGG_DB_USER
        ports:
        - containerPort: 5000
        resources: 
          requests: 
            cpu: 64m
            memory: 96Mi
          limits:
            cpu: 64m
            memory: 96Mi
        livenessProbe:
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 5
          httpGet: 
            path: /healthz 
            port: 5000

--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: bggapp-svc 
  namespace: bggns 
  labels:
    app: bggapp-svc 
spec: 
  type: ClusterIP
  selector: 
    app: bggapp-pod
  ports:
  - port: 5000 
    targetPort: 5000

--- 
apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: bgg-ing
  namespace: bggns
spec: 
  ingressClassName: nginx 
  rules: 
  - host: bgg-188.166.197.98.sslip.io
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: bggapp-svc 
            port:
              number: 5000

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bgg-hpa
  namespace: bggns
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: Deployment
    name: bggapp-deploy
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization 
        averageUtilization: 20